---
name: Net-OpenAMD
version: v0.1.0
author:
  - 'Andrew Fresh <andrew@cpan.org>'
abstract: Perl interface to the OpenAMD API
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Mojolicious: 0
  Test::Deep: 0
  Test::More: 0
requires:
  JSON: 0
  LWP::UserAgent: 0
  Net::OAuth: 0
  URI: 0
  version: 0
configure_requires:
  Module::Build: 0.340201
provides:
  Net::OpenAMD:
    file: lib/Net/OpenAMD.pm
    version: v0.1.0
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
